apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smgcp-proxy
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmregler
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: pale-2-regler
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmmottak
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: pale-2
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmpapirregler
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmpapirmottak
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: smregistrering-backend
          namespace: teamsykmelding
          cluster: prod-gcp
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvsmgcpproxy
        mountPath: /secrets/serviceuser
  ingresses:
    - "https://smgcp-proxy.intern.nav.no"
    - "https://smgcp-proxy.prod-fss-pub.nais.io"
  webproxy: true
  env:
    - name: KUHR_SAR_API_SCOPE
      value: api://prod-fss.teamkuhr.kuhr-sar-api/.default
    - name: KUHR_SAR_API_URL
      value: https://kuhr-sar-api.nais.adeo.no
    - name: SUBSCRIPTION_ENDPOINT_URL
      value: https://wasapp.adeo.no/nav-emottak-eletter-web/services/