apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smgcp-proxy
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 50m
      memory: 300Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmottak
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: pale-2
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmpapirmottak
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: padm2
          namespace: teamsykefravr
          cluster: dev-gcp
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvsmgcpproxy
        mountPath: /secrets/serviceuser
  ingresses:
    - "https://smgcp-proxy.dev-fss-pub.nais.io"
  webproxy: true
  env:
    - name: SUBSCRIPTION_ENDPOINT_URL
      value: https://wasapp-q1.adeo.no/nav-emottak-eletter-web/services/
