name: Deploy alert config prod
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/alerts.yml'
      - 'alertconfig.yaml'

jobs:
  apply-alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: alertconfig.yaml