name: Deploy to dev and prod
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-alerts.yml
      - alerts-fss-prod.yaml
      - alerts-fss-dev.yaml
jobs:
  deploy_prod:
    name: Deploy alert til prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_TEAMSYKMELDING_DEPLOY_KEY }}
          CLUSTER: dev-fss
          RESOURCE: alerts-fss-dev.yaml
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_TEAMSYKMELDING_DEPLOY_KEY }}
          CLUSTER: prod-fss
          RESOURCE: alerts-fss-prod.yaml
