name: Deploy app to dev and prod
on: push

permissions:
  actions: read
  contents: write
  security-events: write
  packages: write
  id-token: write

jobs:
  jar-app:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/installdist-gradle-21.yaml@main
    secrets: inherit
    with:
      team: teamsykmelding
      app: smgcp-proxy
      cluster: fss
