name: Deploy alert config dev
on:
  push:
    branches:
      - '*'
      - '!main'
    paths:
      - '.github/workflows/dev-alerts.yml'
      - 'alertconfig-dev.yaml'

jobs:
  apply-alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: alertconfig-dev.yaml